// Code generated by qtc from "item.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/views/components/url/item.qtpl:1
package url

//line ../../pkg/views/components/url/item.qtpl:1
import "smashedbits.com/shorty/pkg/model"

//line ../../pkg/views/components/url/item.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/views/components/url/item.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/views/components/url/item.qtpl:3
func StreamRenderItem(qw422016 *qt422016.Writer, url model.URL) {
//line ../../pkg/views/components/url/item.qtpl:3
	qw422016.N().S(`
<div class="flex items-center justify-center gap-2">
  <a class="link link-neutral" href="`)
//line ../../pkg/views/components/url/item.qtpl:5
	qw422016.E().S(url.Hash)
//line ../../pkg/views/components/url/item.qtpl:5
	qw422016.N().S(`" target="_blank">
    shorty.dev/`)
//line ../../pkg/views/components/url/item.qtpl:6
	qw422016.E().S(url.Hash)
//line ../../pkg/views/components/url/item.qtpl:6
	qw422016.N().S(`
  </a>
</div>
`)
//line ../../pkg/views/components/url/item.qtpl:9
}

//line ../../pkg/views/components/url/item.qtpl:9
func WriteRenderItem(qq422016 qtio422016.Writer, url model.URL) {
//line ../../pkg/views/components/url/item.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/views/components/url/item.qtpl:9
	StreamRenderItem(qw422016, url)
//line ../../pkg/views/components/url/item.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/views/components/url/item.qtpl:9
}

//line ../../pkg/views/components/url/item.qtpl:9
func RenderItem(url model.URL) string {
//line ../../pkg/views/components/url/item.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/views/components/url/item.qtpl:9
	WriteRenderItem(qb422016, url)
//line ../../pkg/views/components/url/item.qtpl:9
	qs422016 := string(qb422016.B)
//line ../../pkg/views/components/url/item.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/views/components/url/item.qtpl:9
	return qs422016
//line ../../pkg/views/components/url/item.qtpl:9
}
