// Code generated by qtc from "list.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/views/components/url/list.qtpl:1
package url

//line ../../pkg/views/components/url/list.qtpl:1
import "smashedbits.com/shorty/pkg/model"

//line ../../pkg/views/components/url/list.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/views/components/url/list.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/views/components/url/list.qtpl:3
func StreamRenderList(qw422016 *qt422016.Writer, urls []model.URL) {
//line ../../pkg/views/components/url/list.qtpl:3
	qw422016.N().S(`
<div class="flex flex-col rounded-box h-[calc(100vh-64px-48px-12rem-32px-52px)] p-2 gap-4">
  <div class="flex flex-col text-primary">
    <h3 class="text-2xl font-bold">Your Shortened URLs</h3>
  </div>
  <div class="overflow-y-auto">
    `)
//line ../../pkg/views/components/url/list.qtpl:9
	for _, url := range urls {
//line ../../pkg/views/components/url/list.qtpl:9
		qw422016.N().S(`
      `)
//line ../../pkg/views/components/url/list.qtpl:10
		StreamRenderItem(qw422016, url)
//line ../../pkg/views/components/url/list.qtpl:10
		qw422016.N().S(`
    `)
//line ../../pkg/views/components/url/list.qtpl:11
	}
//line ../../pkg/views/components/url/list.qtpl:11
	qw422016.N().S(`
  </div>
</div>
`)
//line ../../pkg/views/components/url/list.qtpl:14
}

//line ../../pkg/views/components/url/list.qtpl:14
func WriteRenderList(qq422016 qtio422016.Writer, urls []model.URL) {
//line ../../pkg/views/components/url/list.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/views/components/url/list.qtpl:14
	StreamRenderList(qw422016, urls)
//line ../../pkg/views/components/url/list.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/views/components/url/list.qtpl:14
}

//line ../../pkg/views/components/url/list.qtpl:14
func RenderList(urls []model.URL) string {
//line ../../pkg/views/components/url/list.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/views/components/url/list.qtpl:14
	WriteRenderList(qb422016, urls)
//line ../../pkg/views/components/url/list.qtpl:14
	qs422016 := string(qb422016.B)
//line ../../pkg/views/components/url/list.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/views/components/url/list.qtpl:14
	return qs422016
//line ../../pkg/views/components/url/list.qtpl:14
}
