// Code generated by qtc from "footer.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/views/components/nav/footer.qtpl:1
package nav

//line ../../pkg/views/components/nav/footer.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/views/components/nav/footer.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/views/components/nav/footer.qtpl:1
func StreamRenderFooter(qw422016 *qt422016.Writer) {
//line ../../pkg/views/components/nav/footer.qtpl:1
	qw422016.N().S(`
<footer class="footer footer-center p-4 bg-primary text-primary-content">
  <aside>
    <p class="text-white">Made with ☕ by <a href="https://x.com/sammycodes">Sammy</a></p>
  </aside>
</footer>
`)
//line ../../pkg/views/components/nav/footer.qtpl:7
}

//line ../../pkg/views/components/nav/footer.qtpl:7
func WriteRenderFooter(qq422016 qtio422016.Writer) {
//line ../../pkg/views/components/nav/footer.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/views/components/nav/footer.qtpl:7
	StreamRenderFooter(qw422016)
//line ../../pkg/views/components/nav/footer.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/views/components/nav/footer.qtpl:7
}

//line ../../pkg/views/components/nav/footer.qtpl:7
func RenderFooter() string {
//line ../../pkg/views/components/nav/footer.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/views/components/nav/footer.qtpl:7
	WriteRenderFooter(qb422016)
//line ../../pkg/views/components/nav/footer.qtpl:7
	qs422016 := string(qb422016.B)
//line ../../pkg/views/components/nav/footer.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/views/components/nav/footer.qtpl:7
	return qs422016
//line ../../pkg/views/components/nav/footer.qtpl:7
}
