// Code generated by qtc from "header.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/views/components/nav/header.qtpl:1
package nav

//line ../../pkg/views/components/nav/header.qtpl:1
import "strings"

//line ../../pkg/views/components/nav/header.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/views/components/nav/header.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/views/components/nav/header.qtpl:3
func StreamRenderHeader(qw422016 *qt422016.Writer, userId string, userEmail string) {
//line ../../pkg/views/components/nav/header.qtpl:3
	qw422016.N().S(`
<div class="navbar bg-base-100">
  <div class="navbar-start">
    <a href="/" class="btn btn-ghost text-xl font-bold text-primary">SHORTY</a>
  </div>
  <div class="navbar-end gap-2">
    <label class="cursor-pointer grid place-items-center">
      <input type="checkbox" value="dark"
        class="toggle theme-controller bg-primary hover:bg-primary row-start-1 col-start-1 col-span-2 border-primary" />
      <svg class="col-start-1 row-start-1 stroke-base-100 fill-base-100" xmlns="http://www.w3.org/2000/svg" width="14"
        height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
        stroke-linejoin="round">
        <circle cx="12" cy="12" r="5" />
        <path d="M12 1v2M12 21v2M4.2 4.2l1.4 1.4M18.4 18.4l1.4 1.4M1 12h2M21 12h2M4.2 19.8l1.4-1.4M18.4 5.6l1.4-1.4" />
      </svg>
      <svg class="col-start-2 row-start-1 stroke-base-100 fill-base-100" xmlns="http://www.w3.org/2000/svg" width="14"
        height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
        stroke-linejoin="round">
        <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
      </svg>
    </label>
    `)
//line ../../pkg/views/components/nav/header.qtpl:24
	if userId != "" {
//line ../../pkg/views/components/nav/header.qtpl:24
		qw422016.N().S(`
    <div class="dropdown dropdown-end">
      <label tabindex="0" class="btn btn-ghost btn-circle avatar">
        <div class="avatar placeholder">
          <div class="bg-primary text-neutral-content rounded-full w-8">
            <span class="text-lg">`)
//line ../../pkg/views/components/nav/header.qtpl:29
		if userEmail != "" {
//line ../../pkg/views/components/nav/header.qtpl:29
			qw422016.E().S(strings.ToUpper(userEmail[0:1]))
//line ../../pkg/views/components/nav/header.qtpl:29
		}
//line ../../pkg/views/components/nav/header.qtpl:29
		qw422016.N().S(`</span>
          </div>
        </div>
      </label>
      <ul tabindex="0" class="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-52">
        <li><a href="/auth/logout">Logout</a></li>
      </ul>
    </div>
    `)
//line ../../pkg/views/components/nav/header.qtpl:37
	} else {
//line ../../pkg/views/components/nav/header.qtpl:37
		qw422016.N().S(`
      <a href="/auth" class="btn btn-sm btn-secondary">Sign in</a>
    `)
//line ../../pkg/views/components/nav/header.qtpl:39
	}
//line ../../pkg/views/components/nav/header.qtpl:39
	qw422016.N().S(`
  </div>
</div>
`)
//line ../../pkg/views/components/nav/header.qtpl:42
}

//line ../../pkg/views/components/nav/header.qtpl:42
func WriteRenderHeader(qq422016 qtio422016.Writer, userId string, userEmail string) {
//line ../../pkg/views/components/nav/header.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/views/components/nav/header.qtpl:42
	StreamRenderHeader(qw422016, userId, userEmail)
//line ../../pkg/views/components/nav/header.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/views/components/nav/header.qtpl:42
}

//line ../../pkg/views/components/nav/header.qtpl:42
func RenderHeader(userId string, userEmail string) string {
//line ../../pkg/views/components/nav/header.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/views/components/nav/header.qtpl:42
	WriteRenderHeader(qb422016, userId, userEmail)
//line ../../pkg/views/components/nav/header.qtpl:42
	qs422016 := string(qb422016.B)
//line ../../pkg/views/components/nav/header.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/views/components/nav/header.qtpl:42
	return qs422016
//line ../../pkg/views/components/nav/header.qtpl:42
}
