// Code generated by qtc from "auth.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/views/pages/auth.qtpl:1
package pages

//line ../../pkg/views/pages/auth.qtpl:1
import "smashedbits.com/shorty/pkg/views/components/auth"

//line ../../pkg/views/pages/auth.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/views/pages/auth.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/views/pages/auth.qtpl:4
type Auth struct {
	UserIdStg    string
	UserEmailStg string
}

//line ../../pkg/views/pages/auth.qtpl:9
func (a *Auth) StreamTitle(qw422016 *qt422016.Writer) {
//line ../../pkg/views/pages/auth.qtpl:9
	qw422016.N().S(`Sign in to continue`)
//line ../../pkg/views/pages/auth.qtpl:9
}

//line ../../pkg/views/pages/auth.qtpl:9
func (a *Auth) WriteTitle(qq422016 qtio422016.Writer) {
//line ../../pkg/views/pages/auth.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/views/pages/auth.qtpl:9
	a.StreamTitle(qw422016)
//line ../../pkg/views/pages/auth.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/views/pages/auth.qtpl:9
}

//line ../../pkg/views/pages/auth.qtpl:9
func (a *Auth) Title() string {
//line ../../pkg/views/pages/auth.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/views/pages/auth.qtpl:9
	a.WriteTitle(qb422016)
//line ../../pkg/views/pages/auth.qtpl:9
	qs422016 := string(qb422016.B)
//line ../../pkg/views/pages/auth.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/views/pages/auth.qtpl:9
	return qs422016
//line ../../pkg/views/pages/auth.qtpl:9
}

//line ../../pkg/views/pages/auth.qtpl:10
func (a *Auth) StreamUserId(qw422016 *qt422016.Writer) {
//line ../../pkg/views/pages/auth.qtpl:10
	qw422016.E().S(a.UserIdStg)
//line ../../pkg/views/pages/auth.qtpl:10
}

//line ../../pkg/views/pages/auth.qtpl:10
func (a *Auth) WriteUserId(qq422016 qtio422016.Writer) {
//line ../../pkg/views/pages/auth.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/views/pages/auth.qtpl:10
	a.StreamUserId(qw422016)
//line ../../pkg/views/pages/auth.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/views/pages/auth.qtpl:10
}

//line ../../pkg/views/pages/auth.qtpl:10
func (a *Auth) UserId() string {
//line ../../pkg/views/pages/auth.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/views/pages/auth.qtpl:10
	a.WriteUserId(qb422016)
//line ../../pkg/views/pages/auth.qtpl:10
	qs422016 := string(qb422016.B)
//line ../../pkg/views/pages/auth.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/views/pages/auth.qtpl:10
	return qs422016
//line ../../pkg/views/pages/auth.qtpl:10
}

//line ../../pkg/views/pages/auth.qtpl:11
func (a *Auth) StreamUserEmail(qw422016 *qt422016.Writer) {
//line ../../pkg/views/pages/auth.qtpl:11
	qw422016.E().S(a.UserEmailStg)
//line ../../pkg/views/pages/auth.qtpl:11
}

//line ../../pkg/views/pages/auth.qtpl:11
func (a *Auth) WriteUserEmail(qq422016 qtio422016.Writer) {
//line ../../pkg/views/pages/auth.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/views/pages/auth.qtpl:11
	a.StreamUserEmail(qw422016)
//line ../../pkg/views/pages/auth.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/views/pages/auth.qtpl:11
}

//line ../../pkg/views/pages/auth.qtpl:11
func (a *Auth) UserEmail() string {
//line ../../pkg/views/pages/auth.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/views/pages/auth.qtpl:11
	a.WriteUserEmail(qb422016)
//line ../../pkg/views/pages/auth.qtpl:11
	qs422016 := string(qb422016.B)
//line ../../pkg/views/pages/auth.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/views/pages/auth.qtpl:11
	return qs422016
//line ../../pkg/views/pages/auth.qtpl:11
}

//line ../../pkg/views/pages/auth.qtpl:13
func (a *Auth) StreamBody(qw422016 *qt422016.Writer) {
//line ../../pkg/views/pages/auth.qtpl:13
	qw422016.N().S(`
<div class="hero h-[calc(100vh-64px-52px)]">
  <div class="hero-overlay bg-opacity-60 bg-primary"></div>
  <div class="hero-content text-center text-neutral-content">
    <div class="max-w-md">
      <div class="card w-96 bg-base-100 shadow-xl">
        <div class="card-body items-center text-center">
          <h1 class="mb-2 text-xl lg:text-4xl font-bold text-primary">Let's Start shortening!</h1>
          <p class="mb-2 lg:text-xl text-primary">Create an account with one of the following methods</p>
          `)
//line ../../pkg/views/pages/auth.qtpl:22
	auth.StreamRenderGoogleProvider(qw422016)
//line ../../pkg/views/pages/auth.qtpl:22
	qw422016.N().S(`
        </div>
      </div>
    </div>
  </div>
</div>
`)
//line ../../pkg/views/pages/auth.qtpl:28
}

//line ../../pkg/views/pages/auth.qtpl:28
func (a *Auth) WriteBody(qq422016 qtio422016.Writer) {
//line ../../pkg/views/pages/auth.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/views/pages/auth.qtpl:28
	a.StreamBody(qw422016)
//line ../../pkg/views/pages/auth.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/views/pages/auth.qtpl:28
}

//line ../../pkg/views/pages/auth.qtpl:28
func (a *Auth) Body() string {
//line ../../pkg/views/pages/auth.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/views/pages/auth.qtpl:28
	a.WriteBody(qb422016)
//line ../../pkg/views/pages/auth.qtpl:28
	qs422016 := string(qb422016.B)
//line ../../pkg/views/pages/auth.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/views/pages/auth.qtpl:28
	return qs422016
//line ../../pkg/views/pages/auth.qtpl:28
}
