// Code generated by qtc from "landing.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/views/pages/landing.qtpl:1
package pages

//line ../../pkg/views/pages/landing.qtpl:1
import "smashedbits.com/shorty/pkg/model"

//line ../../pkg/views/pages/landing.qtpl:2
import urltpl "smashedbits.com/shorty/pkg/views/components/url"

//line ../../pkg/views/pages/landing.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/views/pages/landing.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/views/pages/landing.qtpl:5
type Landing struct {
	UserIdStg    string
	UserEmailStg string
	Urls         []model.URL
}

//line ../../pkg/views/pages/landing.qtpl:11
func (l *Landing) StreamTitle(qw422016 *qt422016.Writer) {
//line ../../pkg/views/pages/landing.qtpl:11
	qw422016.N().S(`This is a base title`)
//line ../../pkg/views/pages/landing.qtpl:11
}

//line ../../pkg/views/pages/landing.qtpl:11
func (l *Landing) WriteTitle(qq422016 qtio422016.Writer) {
//line ../../pkg/views/pages/landing.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/views/pages/landing.qtpl:11
	l.StreamTitle(qw422016)
//line ../../pkg/views/pages/landing.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/views/pages/landing.qtpl:11
}

//line ../../pkg/views/pages/landing.qtpl:11
func (l *Landing) Title() string {
//line ../../pkg/views/pages/landing.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/views/pages/landing.qtpl:11
	l.WriteTitle(qb422016)
//line ../../pkg/views/pages/landing.qtpl:11
	qs422016 := string(qb422016.B)
//line ../../pkg/views/pages/landing.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/views/pages/landing.qtpl:11
	return qs422016
//line ../../pkg/views/pages/landing.qtpl:11
}

//line ../../pkg/views/pages/landing.qtpl:12
func (l *Landing) StreamUserId(qw422016 *qt422016.Writer) {
//line ../../pkg/views/pages/landing.qtpl:12
	qw422016.E().S(l.UserIdStg)
//line ../../pkg/views/pages/landing.qtpl:12
}

//line ../../pkg/views/pages/landing.qtpl:12
func (l *Landing) WriteUserId(qq422016 qtio422016.Writer) {
//line ../../pkg/views/pages/landing.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/views/pages/landing.qtpl:12
	l.StreamUserId(qw422016)
//line ../../pkg/views/pages/landing.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/views/pages/landing.qtpl:12
}

//line ../../pkg/views/pages/landing.qtpl:12
func (l *Landing) UserId() string {
//line ../../pkg/views/pages/landing.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/views/pages/landing.qtpl:12
	l.WriteUserId(qb422016)
//line ../../pkg/views/pages/landing.qtpl:12
	qs422016 := string(qb422016.B)
//line ../../pkg/views/pages/landing.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/views/pages/landing.qtpl:12
	return qs422016
//line ../../pkg/views/pages/landing.qtpl:12
}

//line ../../pkg/views/pages/landing.qtpl:13
func (l *Landing) StreamUserEmail(qw422016 *qt422016.Writer) {
//line ../../pkg/views/pages/landing.qtpl:13
	qw422016.E().S(l.UserEmailStg)
//line ../../pkg/views/pages/landing.qtpl:13
}

//line ../../pkg/views/pages/landing.qtpl:13
func (l *Landing) WriteUserEmail(qq422016 qtio422016.Writer) {
//line ../../pkg/views/pages/landing.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/views/pages/landing.qtpl:13
	l.StreamUserEmail(qw422016)
//line ../../pkg/views/pages/landing.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/views/pages/landing.qtpl:13
}

//line ../../pkg/views/pages/landing.qtpl:13
func (l *Landing) UserEmail() string {
//line ../../pkg/views/pages/landing.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/views/pages/landing.qtpl:13
	l.WriteUserEmail(qb422016)
//line ../../pkg/views/pages/landing.qtpl:13
	qs422016 := string(qb422016.B)
//line ../../pkg/views/pages/landing.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/views/pages/landing.qtpl:13
	return qs422016
//line ../../pkg/views/pages/landing.qtpl:13
}

//line ../../pkg/views/pages/landing.qtpl:15
func (l *Landing) StreamBody(qw422016 *qt422016.Writer) {
//line ../../pkg/views/pages/landing.qtpl:15
	qw422016.N().S(`
<div class="hero h-[calc(100vh-64px-52px)]">
  <div class="hero-overlay bg-opacity-60 bg-primary"></div>
  <div class="hero-content text-center text-neutral-content">
    <div class="flex flex-col justify-between gap-4">
      <div class="max-w-md">
        <h1 class="mb-6 text-5xl font-bold text-white">Shorter Links, Bigger Connections</h1>
        <div class="join w-full">
          <form hx-post="/url" enctype="multipart/form-data" hx-swap="innerHTML" hx-target="#urlList"
            class="join w-full mx-4 lg:mx-0">
            <input type="text" required name="long_url" placeholder="insert your link here..."
              class="input input-bordered input-primary w-full join-item text-gray-600" />
            <button class="btn btn-primary join-item text-white">Shorten it!</button>
          </form>
        </div>
      </div>
      <div id="urlList">
        `)
//line ../../pkg/views/pages/landing.qtpl:32
	urltpl.StreamRenderList(qw422016, l.Urls)
//line ../../pkg/views/pages/landing.qtpl:32
	qw422016.N().S(`
      </div>
    </div>
  </div>
</div>
`)
//line ../../pkg/views/pages/landing.qtpl:37
}

//line ../../pkg/views/pages/landing.qtpl:37
func (l *Landing) WriteBody(qq422016 qtio422016.Writer) {
//line ../../pkg/views/pages/landing.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/views/pages/landing.qtpl:37
	l.StreamBody(qw422016)
//line ../../pkg/views/pages/landing.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/views/pages/landing.qtpl:37
}

//line ../../pkg/views/pages/landing.qtpl:37
func (l *Landing) Body() string {
//line ../../pkg/views/pages/landing.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/views/pages/landing.qtpl:37
	l.WriteBody(qb422016)
//line ../../pkg/views/pages/landing.qtpl:37
	qs422016 := string(qb422016.B)
//line ../../pkg/views/pages/landing.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/views/pages/landing.qtpl:37
	return qs422016
//line ../../pkg/views/pages/landing.qtpl:37
}
